version: "3.4"

services:
  app:
    build:
      context: .
    networks:
      - minharede
    volumes:
      - ./nodeapp:/usr/src/app
    tty: true
    restart: always
    ports:
      - "3001:3001"
    container_name: nodeapp
  database:
    image: postgres
    container_name: database
    restart: always
    tty: true
    env_file: .env
    ports:
      - "5432:5432"

    networks:
      - minharede

networks:
  minharede:
    driver: bridge

volumes:
  mysql:
